language: java
before_install:
  - chmod +x mvnw
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - ./mvnw clean install
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT